### ISSUE TITLE
sorry, i install deb in ubuntu20.04,but when i use it to load input jpg ,it crash,how can i get the log to find result

### ISSUE THREAD

**Issue by mathpopo** [zetane/viewer#14]
(base) chenxin@chenxin-Nitro-AN515-52:~/下载$ sudo dpkg -i Zetane-1.7.0.deb 
(正在读取数据库 ... 系统当前共安装有 330200 个文件和目录。)
准备解压 Zetane-1.7.0.deb  ...
正在解压 zetane (1.7.0) 并覆盖 (1.7.0) ...
正在设置 zetane (1.7.0) ...
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu3) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...

**Comment by konafah** [comment]
Hello, thank you for the error report. The logs can be found in:

* macOS: `~/Library/Application\ Support/Zetane/logs`
* Ubuntu: `~/.config/Zetane/logs`
* Windows: `%APPDATA%/Zetane/logs`

You can also email me directly at omar@zetane.com

**Comment by konafah** [comment]
Hi, we were able to reproduce a similar crash. It's mainly due to shape mismatch between the input data (jpg) and the model input shape. We're releasing a fix for the crash + improved error messaging in an upcoming release.

In the meantime, try loading a correctly shaped .npy (using the same button you used to load the input jpg). Thanks.
